tabs:
  pages:
    label: Site
    icon: settings
    columns:
      - width: 1/3
        sections:
          mainpages:
            type: pages
            status: listed
            headline: Pages principales
            image:
              back: black
      - width: 1/3
        sections:
          unlistedpages:
            type: pages
            status: unlisted
            headline: Pages non référencées
            image:
              back: black
      - width: 1/3
        sections:
          listed:
            headline: Pages brouillon
            type: pages
            status: draft
      - width: 2/3
        fields:
          line:
            type: line
      - width: 1
        sections:
          - sections/navigation-menus
      - width: 1
        fields:
          footer:
            label: Pied de page
            extends: fields/layout
  seo:
    label: SEO
    extends: seo/site
  resources:
    label: Ressources
    icon: lab
    columns:
      - width: 2/3
        sections:
          draftResources:
            extends: sections/resources
            label: Ressources en brouillon
            status: draft
            empty: Aucune ressource n'est en mode brouillon
            limit: 6
            columns:
              year: true
              clientName: true
              projectName: true
      - width: 1/3
        sections:
          resourcetypes:
            type: fields
            fields:
              resourcetypes:
                extends: sections/resourcetypes
      - width: 1
        sections:
          publishedResources:
            extends: sections/resources
            label: Ressources publiées
            status: listed
            empty: Aucune ressource n'est publiée
            layout: cards
            limit: 200
            columns:
              year: true
              clientName: true
              projectName: true
  humans:
    label: Humains
    icon: users
    columns:
      - width: 2/3
        sections:
          drafthumans:
            extends: sections/humans
            label: Humains en brouillon
            status: draft
            empty: Aucun humain n'est en mode brouillon
            layout: cards
            limit: 6
            size: tiny
          listedhumans:
            extends: sections/humans
            label: Humains publiés
            status: listed
            empty: Aucun humain n'est publié
            layout: cards
            size: small
            limit: 200
      - width: 1/3
        fields:
          senioritylevels:
            extends: fields/seniority-levels
          expertises:
            extends: fields/skills
            label: Expertises
          skills:
            extends: fields/skills
